version: '3.6'
services:
  postgres-staging:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_staging:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  hasura-staging:
    image: hasura/graphql-engine:v2.33.4
    ports:
      - "8080:8080"
    depends_on:
      - "postgres-staging"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres-staging:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

volumes:
  db_data_staging: 