version: '3.6'
services:
  postgres-production:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_production:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Note: Different port from staging

  hasura-production:
    image: hasura/graphql-engine:v2.33.4  # Specify version
    ports:
      - "8081:8080"  # Note: Different port from staging
    depends_on:
      - "postgres-production"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres-production:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

volumes:
  db_data_production: 